name: Setup Project
description: Set up Node.js, install deps, lint, and test
inputs:
  node-version:
    description: Node.js version
    default: '18'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Lint
      shell: bash
      run: npm run lint

    - name: Test
      shell: bash
      run: npm test
