name: Scheduled Dependency Audit

on:
  schedule:
    - cron: "0 0 * * *"   # nightly 00:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  security-events: write

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # --- Diagnostics so we can SEE what the runner sees ---
      - name: Debug: show workspace & lockfiles
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
          echo "Found lock files:"
          find . -maxdepth 2 -type f \( -name package.json -o -name package-lock.json -o -name npm-shrinkwrap.json -o -name yarn.lock \) -print

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          # Be explicit + robust. If root has it, the first line is enough;
          # the globs cover edge cases.
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json
            **/npm-shrinkwrap.json
            **/yarn.lock

      - name: Verify lockfile exists at root (fail early if not)
        run: |
          if [ ! -f package-lock.json ]; then
            echo "❌ package-lock.json not found at repo root. See debug step above."
            exit 1
          fi
          echo "✅ package-lock.json present at repo root."

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Run npm audit (moderate+)
        run: npm audit --audit-level=moderate --json > audit.json || true

      - name: Create or update issue for high/critical vulns
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const core = require('@actions/core');
            const data = JSON.parse(fs.readFileSync('audit.json', 'utf8'));
            const vulns = data?.metadata?.vulnerabilities || data?.vulnerabilities || {};
            const high = Number(vulns.high || 0);
            const critical = Number(vulns.critical || 0);
            const totalHC = high + critical;

            if (totalHC === 0) {
              core.info('✅ No high/critical vulnerabilities found.');
              return;
            }

            const title = `Security audit: ${high} high / ${critical} critical vulnerabilities`;
            const body = [
              'Automated nightly `npm audit --audit-level=moderate` detected **high/critical** vulnerabilities.',
              '',
              '### Summary',
              '```json',
              JSON.stringify({ high, critical, all: vulns }, null, 2),
              '```',
              '',
              'Re-run locally with:',
              '```bash',
              'npm audit --audit-level=moderate',
              '```',
              '',
              `Generated by GitHub Actions on ${new Date().toISOString()}.`
            ].join('\n');

            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'security-audit'
            });

            if (issues.length) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues[0].number,
                title,
                body
              });
              core.info(`🔁 Updated existing issue #${issues[0].number}.`);
            } else {
              const { data: issue } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title,
                body,
                labels: ['security-audit']
              });
              core.info(`🆕 Created issue #${issue.number}.`);
            }

      - name: Upload audit.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-json
          path: audit.json
          if-no-files-found: ignore
